name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Install requirements
        run: |
          python -m pip install -U pip pipenv
          pipenv sync --system --dev
      - name: Test all
        if: matrix.python-version == '3.10'
        run: make test
      - name: Only Pytest
        if: matrix.python-version != '3.10'
        run: make pytest
