name: Release

on:
  push:
    tags:
      - '*'


jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv wheel
          pipenv sync --system --dev
      - name: Release chinesecalendar
        run: python setup.py sdist bdist_wheel
      - name: Publish chinesecalendar
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_token }}
      - name: Release chinese-calendar
        run: |
          sed -i 's/chinesecalendar/chinese_calendar/g' setup.py
          python setup.py sdist bdist_wheel
      - name: Publish chinese-calendar
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_token }}
